services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: RCE_api
        restart: always
        ports:
            - '3000:3000'
        env_file:
            - .env
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
        volumes:
            - /run/podman/podman.sock:/var/run/docker.sock
        privileged: true

    postgres:
        image: postgres:18.1-alpine
        container_name: code_engine_db
        restart: always
        ports:
            - '5432:5432'
        volumes:
            - code_engine_data:/var/lib/postgresql
        env_file:
            - .env
        healthcheck:
            test:
                ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
            interval: 5s
            timeout: 5s
            retries: 5

    redis:
        image: docker.io/library/redis:7.2
        container_name: redis-db
        restart: always
        ports:
            - '6379:6379'
        volumes:
            - redis-data:/data
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 5s
            timeout: 3s
            retries: 5

volumes:
    code_engine_data:
    redis-data:
