services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: RCE_api
        restart: always
        ports:
            - '3000:3000'
        env_file:
            - .env
        depends_on:
            - postgres
            - redis
        volumes:
            - /run/podman/podman.sock:/var/run/docker.sock

    postgres:
        image: postgres:18.1-alpine
        container_name: code_engine_db
        restart: always
        ports:
            - '5432:5432'
        volumes:
            - code_engine_data:/var/lib/postgresql
        env_file:
            - .env

    redis:
        image: docker.io/library/redis:7.2
        container_name: redis-db
        restart: always
        ports:
            - '6379:6379'
        volumes:
            - redis-data:/data

volumes:
    code_engine_data:
    redis-data:
