// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotEnv from 'dotenv';
import { defineConfig } from 'prisma/config';

dotEnv.config({
    path:
        process.env.NODE_ENV === 'test'
            ? '.env.test'
            : process.env.NODE_ENV === 'development'
              ? '.env.development'
              : '.env',
    override: false,
    encoding: 'utf8',
});

export default defineConfig({
    schema: 'prisma/schema.prisma',
    migrations: {
        path: 'prisma/migrations',
    },
    datasource: {
        url: process.env['DATABASE_URL'],
    },
});
