export enum ParamTypes {
    INT = 'INT',
    FLOAT = 'FLOAT',
    STRING = 'STRING',
    BOOLEAN = 'BOOLEAN',
    INT_ARRAY = 'INT_ARRAY',
    FLOAT_ARRAY = 'FLOAT_ARRAY',
    STRING_ARRAY = 'STRING_ARRAY',
    BOOLEAN_ARRAY = 'BOOLEAN_ARRAY',
}
